### ISSUE TITLE
[question] how to use `emacs --daemon` with the Emacs.app

### ISSUE THREAD

**Issue by robsonpeixoto** [railwaycat/mirror-emacs-mac#1]
How to use `emacs --daemon` with the Emacs.app? Or, how to open a gui using the emacsclient?

Thanks

**Comment by peterhadlaw** [comment]
I don't have the exact answer, but this question has been asked / answered before. The creator of the Emacs Mac Port does not know how to tackle a particular issue where if emacs was started in particular tty/ terminal, it can only be opened in the terminal (i.e. trying to open a client GUI will not work).

Sorry but looks like you'll have to find a different solution. Here is one option: http://melpa.org/#/osx-pseudo-daemon

**Comment by robsonpeixoto** [comment]
Thanks
